# Generated by Django 4.2.16 on 2024-10-31 20:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 10, 31, 20, 58, 4, 75650, tzinfo=datetime.timezone.utc))),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.game')),
                ('players', models.ManyToManyField(to='leaderboard.player')),
            ],
        ),
    ]
