# Generated by Django 4.2.16 on 2024-11-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guild',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
