# Generated by Django 4.2.16 on 2024-11-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_game_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayer',
            name='mu',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='sigma',
            field=models.FloatField(null=True),
        ),
    ]
