# Generated by Django 4.2.16 on 2024-10-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_gameplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='ranking',
            field=models.IntegerField(default=25),
        ),
    ]
