name: Deploy

on: 
  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: SSH_PRIVATE_KEY
    steps:
      - uses: actions/checkout@v2

      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.SSH_USER }}

        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 400 private_key

          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} /bin/bash << 'EOF'
            cd discord_civ_bot
            git pull
            source env/bin/activate
            chmod +x restart
            ./restart
          EOF
